'use client'
import { useState, useEffect } from 'react'
import { useRouter } from 'next/navigation'
import { Link as LinkIcon } from 'lucide-react'
import axios from 'axios'
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import '@fortawesome/fontawesome-free/css/all.min.css';
import { PieChart, Pie, Cell, Tooltip, ResponsiveContainer, Legend } from 'recharts';


const Page = () => {
  const router = useRouter()
  const [website, setWebsite] = useState("")
  const [result, setResult] = useState(null)
  const [loading, setLoading] = useState(false)

useEffect(() => {
    const token = localStorage.getItem("token")
    if (!token) {
      if (!window.hasShownAlert) {
        window.hasShownAlert = true;
      alert("Please login first to use this tool!")
      router.push('/signin')
      setTimeout(() => { window.hasShownAlert = false; }, 3000);
      } 
    }
  }, [])

const handleSubmit = async (e) => {
  e.preventDefault();
  setResult(null); 
  setLoading(true);
  setSitemapMissing(false); // 🟢 Sabse pehle purani warning chhupayein

  try {
    const token = localStorage.getItem("token");
    const res = await axios.post(
      "https://orphan-and-broken-page-checker.onrender.com/api/orphan",
      { website },
      { headers: { Authorization: `Bearer ${token}` } }
    );

    console.log("Backend Se Data Aaya:", res.data);

    // 🛑 Check: Agar sitemapExists backend se FALSE aaya hai
    if (res.data.sitemapExists === false) {
      setSitemapMissing(true); // Red warning box dikhayein
      setResult(null); // Result hide rakhein
    } else {
      // ✅ Agar sitemap mila hai (Flag is True)
      setResult(res.data); // Result dikhayein
      setSitemapMissing(false); // Warning band karein
    }
  } catch (error) {
    console.error("Request failed:", error);
    // 500 Error aane par bhi block dikha sakte hain
    setSitemapMissing(true); 
  } finally {
    setLoading(false);
  }
};

const downloadOrphanPDF = async () => {
  const doc = new jsPDF('p', 'mm', 'a4');
  const today = new Date().toLocaleDateString('en-GB');

  // 1. CALCULATIONS (Variables ko define kiya taaki error na aaye)
  const healthy = (result.totalInSitemap || 0) - (result.count || 0);
  const orphan = result.count || 0;
  const total = healthy + orphan;
  const healthScore = total > 0 ? ((healthy / total) * 100).toFixed(1) : 0;


  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("REPORT GENERATED BY LINKSENTINEL.COM", 195, 21, { align: "right" });

  doc.setDrawColor(220);
  doc.line(15, 33, 195, 33); 
  // --- 3. TITLE & WEBSITE INFO ---
 doc.setFont("helvetica", "bold");
doc.setFontSize(18);
doc.setTextColor(30, 41, 59);
doc.text("Orphan Page Analysis", 15, 42); 

// 2. Target Website (URL Button Look)
const targetBoxY = 48;
doc.setFillColor(248, 250, 252);
doc.setDrawColor(220);
doc.roundedRect(15, targetBoxY, 130, 12, 2, 2, "FD");

// Orange Badge
doc.setFillColor(237, 109, 7);
doc.roundedRect(17, targetBoxY + 2, 32, 8, 1, 1, "F");
doc.setFontSize(7.5);
doc.setTextColor(255);
doc.text("TARGET WEBSITE", 33, targetBoxY + 7.5, { align: "center" });

// Website URL
doc.setFontSize(9);
doc.setTextColor(30, 41, 59);
doc.setFont("helvetica", "normal");
doc.text(website, 52, targetBoxY + 7.5);

// Date 
doc.setTextColor(120);
doc.text(`Date: ${today}`, 195, targetBoxY + 7.5, { align: "right" });


const summaryY = 65;
doc.setFillColor(245, 245, 245);
doc.roundedRect(15, summaryY, 180, 12, 2, 2, "F");

doc.setFontSize(10);
doc.setTextColor(60);

doc.text(`Healthy: ${healthy}`, 25, summaryY + 8); 
doc.setTextColor(239, 68, 68);
doc.text(`Orphan: ${orphan}`, 85, summaryY + 8);
doc.setTextColor(60);
doc.text(`Health Score: ${healthScore}%`, 145, summaryY + 8);

 
  // pdf pie chart section
 const boxX = 120;
const boxY = 85;
const boxWidth = 75;
const boxHeight = 62;

// Draw box
doc.setFillColor(252, 252, 252);
doc.setDrawColor(240);
doc.roundedRect(boxX, boxY, boxWidth, boxHeight, 3, 3, "FD");

// Title
doc.setFontSize(11);
doc.setTextColor(30, 41, 59);

doc.setFont("helvetica", "bold");
doc.text("Visual Analysis", boxX + boxWidth / 2, boxY + 10, { align: "center" });

//  Now calculate center AFTER defining box
const centerX = boxX + boxWidth / 2;
const centerY = boxY + boxHeight / 2 - 1;
const radius = 18;

doc.setLineWidth(0);
doc.setLineJoin("round");
doc.setLineCap("round");

if (total > 0) {

  const orphanFraction = orphan / total;
  const orphanAngle = orphanFraction * 2 * Math.PI;

  const healthyPercent = total > 0 ? ((healthy / total) * 100).toFixed(1) : 0;
const orphanPercent = total > 0 ? ((orphan / total) * 100).toFixed(1) : 0;

  
  doc.setFillColor(16, 185, 129);
  doc.circle(centerX, centerY, radius, "F");



  
  if (orphan > 0) {

  doc.setFillColor(239, 68, 68);
  doc.setLineWidth(0);

  const startAngle = -Math.PI / 2;
  const endAngle = startAngle + orphanAngle;

  
  doc.moveTo(centerX, centerY);

  const steps = 100; 
  for (let i = 0; i <= steps; i++) {
    const angle = startAngle + (i / steps) * (endAngle - startAngle);
    const x = centerX + radius * Math.cos(angle);
    const y = centerY + radius * Math.sin(angle);
    doc.lineTo(x, y);
  }

  doc.lineTo(centerX, centerY);
  doc.fill("F");
}

  
  doc.setFillColor(255, 255, 255);
  doc.circle(centerX, centerY, 10, "F");

  const legendY = boxY + boxHeight - 12; 

doc.setFontSize(8);
doc.setFont("helvetica", "normal");
doc.setTextColor(60);


doc.setFillColor(16, 185, 129);
doc.rect(boxX + 10, legendY, 4, 4, "F");

doc.text(
  `Healthy: ${healthyPercent}%`,
  boxX + 18,
  legendY + 3
);


doc.setFillColor(239, 68, 68);
doc.rect(boxX + boxWidth / 2, legendY, 4, 4, "F");

doc.text(
  `Orphan: ${orphanPercent}%`,
  boxX + boxWidth / 2 + 8,
  legendY + 3
);
}
  // end pdf pie chart section

  // --- 5. DATA TABLE ---
  const pageWidth = doc.internal.pageSize.getWidth();


const tableStartX = 15;
const tableEndX = 110;
const tableWidth = tableEndX - tableStartX;

autoTable(doc, {
  startY: 85,
  margin: {
    left: tableStartX,
    right: pageWidth - tableEndX
  },

  head: [['Sr.', 'Orphan URL Path']],

  body: (result.data || []).map((url, i) => [
    i + 1,
    url
  ]),

  columnStyles: {
    0: { cellWidth: 15 },
    1: { cellWidth: tableWidth - 15 }
  },

  styles: {
    fontSize: 8,
    cellPadding: 3,
    overflow: 'linebreak',
    font: 'helvetica'
  },

  headStyles: {
    fillColor: [237, 109, 7],
    textColor: 255
  },

  theme: 'grid'
});

  
  const pageCount = doc.internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Page ${i} of ${pageCount} - By Linksentinel SEO Report`, 105, 285, { align: "center" });
  }

  doc.save(`LinkSentinel_Report_${today.replace(/\//g, '-')}.pdf`);
};

const [sitemapMissing, setSitemapMissing] = useState(false); 
  return (
    <main className="m-8">
      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
      <h1 className="text-3xl md:text-4xl font-bold font-['Nunito']">Orphan Page Checker</h1>
    <h2 className="text-2xl md:text-3xl font-semibold font-['Nunito']">Find Hidden Pages That Search Engines Can’t Discover</h2>
    <div className="text-base md:text-lg font-['PT Sans'] space-y-1.5">
    <p>Orphan pages are web pages that exist on your website but are not linked from any internal pages. Because search engines rely on internal links to crawl and discover content, orphan pages often remain unindexed or perform poorly in search results.</p>
    <p>This <span className="font-bold">Orphan Page Checker</span> analyzes your website structure using your sitemap and internal links to accurately identify orphan pages.</p>
    <p className='font-bold'>Note: <span className='font-normal'>*A valid XML sitemap is required for this analysis.*</span></p>
    </div>
      </section>

      
    
<form onSubmit={handleSubmit} className="mt-2 p-4 ">
  <label
    htmlFor="website-url"
    className="text-2xl font-['Nunito'] text-black"
  >
    Enter your website URL
  </label>

  <div className="flex items-center gap-3 mt-2">
    {/* Input */}
    <div className="flex items-center border-2 gap-2.5 p-2.5 border-gray-500 rounded-md w-[340px]">
      <LinkIcon size={20} absoluteStrokeWidth />
      <input
        className="text-black outline-none flex-1"
        type="url"
        id="website-url"
        placeholder="https://example.com"
        value={website}                     
        onChange={(e) => setWebsite(e.target.value)}
        required
      />
    </div>
    {/* Button */}
    <button
      type="submit"
      className="finline-flex items-center justify-center px-3 py-2 mr-3 text-xl font-['Lora'] font-medium text-center text-white rounded-lg bg-red-600 ring-2 ring-red-600 ring-offset-2 cursor-pointer transition-transform transform hover:scale-95"
    >
      <i className="fa-brands fa-searchengin fa-lg"></i>
      <span>Analysis</span>
    </button>
  </div>
  {/* note text  */}
  <p className="mt-2 text-red-600 text-sm">
    *Make sure your Website Url is valid.
  </p>
</form>

{loading && (
  <div className="mt-4 p-4 bg-blue-50 border-l-4 border-blue-500 text-blue-700 animate-pulse">
    <p className="font-bold font-['PT Sans'] text-xl">Processing Analysis...</p>
    <p className="text-sm italic text-gray-600">The tool is scanning your sitemap and crawling internal links. Please wait.</p>
  </div>
)}

{/* Sitemap Missing Message */}
{sitemapMissing && !loading && (
  <div className="mt-6 p-6 bg-red-50 border-2 border-red-200 rounded-2xl shadow-sm">
    <div className="flex items-start gap-4">
      <div className="bg-red-500 p-2 rounded-full text-white">
        <i className="fa-solid fa-file-circle-xmark text-xl"></i>
      </div>
      <div>
        <h3 className="text-xl font-bold text-red-700 font-['Nunito']">Analysis Blocked!</h3>
        <p className="text-gray-700 mt-1 font-['PT Sans']">
          This Website (<span className="font-bold underline">{website}</span>) not having <span className="font-bold">sitemap.xml</span> file. 
        </p>
        <p className="text-sm text-gray-600 mt-2 bg-white p-2 rounded border italic font-['PT Sans']">
          Please ensure your website has a valid sitemap.xml file at the root directory (e.g., https://example.com/sitemap.xml) and try again.
        </p>
      </div>
    </div>
  </div>
)}

{/*Result */}
{result && (
  <section className="mt-6 p-6 bg-white border-2 border-red-500 rounded-2xl shadow-lg">
    <h2 className="text-2xl md:text-3xl font-semibold font-['Nunito'] text-red-600 mb-6 border-b pb-2 ">
      Orphan Page Report
    </h2>
    
    <div className="flex flex-col md:flex-row gap-8 items-start">
     
      <div className="w-full md:w-3/5">
        
        <div className="grid grid-cols-2 gap-4 mb-6">
          <div className="p-4 bg-gray-100 rounded-lg border border-gray-200 shadow-sm">
            <p className="text-gray-500 font-bold text-[10px] uppercase tracking-wider">Total Sitemap URLs</p>
            <p className="text-4xl font-bold text-gray-800">{result.totalInSitemap || 0}</p> 
          </div>
          <div className="p-4 bg-red-50 rounded-lg border border-red-100 shadow-sm">
            <p className="text-red-700 font-bold text-[10px] uppercase tracking-wider">Orphan Pages Found</p>
            <p className="text-4xl font-bold text-red-600">{result.count || 0}</p>
          </div>
        </div>

        {/* Scrollable URL List */}
        <h3 className="font-bold text-lg mb-2 font-['Nunito'] text-black">Detected URLs:</h3>
        <div className="max-h-64 overflow-y-auto border-2 border-gray-100 p-3 rounded-xl bg-gray-50 shadow-inner scrollbar-thin scrollbar-thumb-gray-300">
          <ul className="list-disc pl-5 space-y-2">
            {(result.data || []).map((url, index) => (
              <li key={index} className="text-blue-600 text-sm break-all font-['PT Sans'] hover:text-red-600 transition-colors">
                {url}
              </li>
            ))}
            {(!result.data || result.data.length === 0) && (
              <p className="text-green-600 font-bold italic text-center p-4">Zero Orphan Pages Found!</p>
            )}
          </ul>
        </div>
       
      </div>

      {/* RIGHT SIDE: Visual Analysis & PDF Button Below */}
      <div className="w-full md:w-2/5 flex flex-col items-center">
        {/* Pie Chart Box */}
        <div id="orphanChart" className="w-full bg-white p-4 rounded-xl border border-gray-100 flex flex-col items-center mb-4">
          <h3 className="text-center font-bold text-gray-700 mb-2 font-['Nunito'] text-sm">Visual Analysis</h3>
          <div id="chartArea" className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={[
                    { name: 'Healthy Pages', value: (result.totalInSitemap || 0) - (result.count || 0) },
                    { name: 'Orphan Pages', value: result.count || 0 },
                  ]}
                  cx="50%" cy="50%" innerRadius={60} outerRadius={85} paddingAngle={5} dataKey="value"
                >
                  <Cell fill="#10B981" /> {/* Green for Healthy */}
                  <Cell fill="#EF4444" /> {/* Red for Orphan */}
                </Pie>
                <Tooltip />
                <Legend verticalAlign="bottom" height={36} />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        {/* Download Button*/}
        <button 
          onClick={downloadOrphanPDF}
          className="w-full bg-[#ED6D07] hover:bg-orange-600 text-white px-5 py-3 rounded-lg font-bold flex items-center justify-center gap-2 cursor-pointer shadow-lg transition-all active:scale-95"
        >
          <i className="fa-solid fa-file-pdf"></i> Download PDF Report
        </button>
      </div>
    </div>
  </section>
)}

<section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Nunito']">How the Orphan Page Checker Works.</h2>
        <p className="text-base md:text-lg font-['PT Sans']">This tool follows a structured analysis process to ensure accurate results.</p>
        <p className="text-base md:text-lg font-semibold font-['PT Sans']">Step-by-Step Process:</p>
        <ol className="list-decimal pl-6 mt-2 text-base md:text-lg font-['PT Sans']">
          <li>The tool searches for an XML sitemap on your website.</li> 
          <li>All URLs listed in the sitemap are collected.</li>
          <li>The tool crawls your website to identify internally linked pages.</li>
          <li>Sitemap URLs are compared with internally linked URLs.</li>
          <li>Pages present in the sitemap but missing internal links are identified as <span className='font-bold'>Orphan Pages</span>.</li>
        </ol>
        <p className="text-lg font-semibold  font-['PT Sans']">Note: <span className='font-normal text-lg'>*If no sitemap is found, the analysis will not run.*</span></p>
      </section>

      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Nunito']">Why a Sitemap Is Required</h2>
        <p className="text-base md:text-lg font-['PT Sans']">A sitemap provides a complete list of pages that exist on your website.</p>
        <p className="text-base md:text-lg font-['PT Sans']">Without it, the tool cannot determine whether a page exists but lacks internal links.</p>
        <p className="text-base md:text-lg font-semibold font-['PT Sans']">Sitemap Benefits:</p>
        <ul className="list-disc pl-6 mt-2 text-base md:text-lg font-['PT Sans']">
          <li>Helps search engines discover all pages</li> 
          <li>Acts as a reference for orphan page detection.</li>
          <li>Improves crawling efficiency.</li>
        </ul>
        <p className="text-base md:text-lg font-['PT Sans']">Without a sitemap, orphan page analysis is not possible.</p>
      </section>

      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Nunito']">Why Orphan Pages Are Bad for SEO</h2>
        <p className="text-base md:text-lg font-['PT Sans']">Orphan pages can negatively impact your website’s SEO performance in several ways:</p>
        <ul className="list-disc pl-6 mt-2 text-base md:text-lg font-['PT Sans']">
          <li>Search engines may not crawl or index them.</li> 
          <li>No internal link authority is passed.</li>
          <li>Reduced visibility in search results.</li>
          <li>Wasted content and ranking potential.</li>
        </ul>
        <p className="text-lg font-normal font-['PT Sans']">Fixing orphan pages helps improve crawlability, indexing, and overall website health.</p>
      </section>

      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Nunito']">How to Fix Orphan Pages</h2>
        <p className="text-base md:text-lg font-['PT Sans']">Once orphan pages are identified, you should:</p>
        <ul className="list-disc pl-6 mt-2 text-base md:text-lg font-['PT Sans']">
          <li>Add internal links from relevant pages.</li> 
          <li>Include them in navigation or category pages.</li>
          <li>Improve your internal linking structure.</li>
          <li>Update sitemap after fixing links.</li>
        </ul>
        <p className="text-lg font-normal font-['PT Sans']">These steps help search engines properly discover and rank your content.</p>
      </section>

      <section className="mt-4 p-4 bg-gray-100 rounded-2xl">
        <h2 className="text-2xl md:text-3xl font-bold font-['Nunito']">Who Should Use This Tool</h2>
        <p className="text-base md:text-lg font-['PT Sans']">This tool is ideal for:</p>
        <ul className="list-disc pl-6 mt-2 text-base md:text-lg font-['PT Sans']">
          <li>SEO professionals.</li> 
          <li>Website owners.</li>
          <li>Digital marketers.</li>
          <li>Developers managing large websites.</li>
          <li>Anyone looking to improve site structure and SEO health.</li>
        </ul>
      </section>    
    </main>
  )
}

export default Page;